apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: yeoman-react2
  title: yeoman-react2
  description: Cookiecutter example
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        system:
          title: System
          type: string
          description: System of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System
            defaultKind: System

    - title: Add Entity Design
      required:
        - name
      type: object  
      properties:
        name:
          title: EntityName
          type: string
          description: Entity name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        EntityDesign:
          title: Entity
          type: array
          description: Feildname
          items:
            type: object
            required:
              - Feildname
            properties: 
              Feildname:
                title: Feildname
                type: string
              Datatype: 
                title: datatype
                type: string
            
    - title: Choose a location
      required:
        - repoUrl
        - dryRun
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false

  steps:
    - id: yeoman
      name: Yeoman
      action: run:yeoman
      input:
        namespace: swdp-react:react-crud
        args:
          - react
        options:
          data:
            com_name: '${{ parameters.name }}' 
            entities:
              - name: employe
                fields:
                   - name: name1
                     datatype: string
                   - name: email2
                     datatype: string
                relations:
                    - name: student
                      fields:
                       - name: name1
                         datatype: string
                       - name: email
                         datatype: string
               
        

    - id: publish
      if: ${{ parameters.dryRun !== true }}
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      if: ${{ parameters.dryRun !== true }}
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - name: Results
      if: ${{ parameters.dryRun }}
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}